
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
</head>
<body bgcolor="#FFFFFF" text="#000000">
<style>
</style>
<!--
<iframe width="640" height="1024" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
        src="https://www.openstreetmap.org/export/embed.html?bbox=13.653653%2C50.9766966%2C13.673653%2C50.9966966&amp;layer=cyclemap&amp;marker=50.9866966%2C13.663653" 
        style="border: 1px solid black">
</iframe><br/>
-->

<?php
    //Creates new record as per request
    //Connect to database
    $servername = 'localhost';
    $username   = 'HeidiTracker';
    $password   = '12wanderfalke34!';
    $dbname     = 'Heidi';
    $Table      = 'TrackerData';
 
    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
        echo "Database Connection failed: " . $conn->connect_error;
        die("Database Connection failed: " . $conn->connect_error);
    }
    
?>
<font size=+3 face="monospace">
<?php
    $CurDate = date('Y-m-d H:i:s');
    $TrackerID = '0001.0001';
    
    $sql  = 'SELECT Longitude, Latitude, Altitude, TimeStamp, Battery, FreeValue2 FROM ' . $Table . ' ';
    $sql .= 'WHERE TrackerID = \'' . $TrackerID . '\' AND TimeStamp <= \'' . $CurDate . '\' ';
    $sql .= 'ORDER BY TimeStamp DESC LIMIT 1';
    
    if ($result=mysqli_query($conn,$sql))
    {
       if ($row=mysqli_fetch_row($result))
      {
           
        $lo = floatval($row[0]);
        $la = floatval($row[1]);

        $lo1 = $lo - 0.012;
        $lo2 = $lo + 0.012;
        $la1 = $la - 0.01;
        $la2 = $la + 0.01;

        $out  = '<iframe ';
        $out .= 'width="1000" height="1200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" ';
        $out .= 'src="https://www.openstreetmap.org/export/embed.html?';
        $out .= 'bbox=' . $lo1 . '%2C' . $la1 . '%2C' . $lo2 . '%2C' . $la2 . '&amp;';
        $out .= 'layer=cyclemap&amp;';
        $out .= 'marker=' . $la . '%2C' . $lo . '" '; 
        $out .= 'style="border: 1px solid black">';
        $out .= '</iframe><br/>';

        echo $out;
       
        echo 'H&ouml;he: ' . $row[2] . '<br>';
        echo 'Zeit: ' . $row[3] . '<br>';
        echo 'Batt: ' . $row[4] . '<br>';
        echo 'Temp: ' . $row[5] . '<br>';
        

      }
      // Free result set
      mysqli_free_result($result);
    }
    mysqli_close($conn);
?>
</font>
</body>
</html>

