<!DOCTYPE html>
<html>
<head>
<!-- 
<meta http-equiv="refresh" content="5"> 
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
</head>
<body bgcolor="#FFFFFF" text="#000000">
<style>
#c4ytable {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#c4ytable td, #c4ytable th {
    border: 1px solid #ddd;
    padding: 8px;
}

#c4ytable tr:nth-child(even){background-color: #f2f2f2;}

#c4ytable tr:hover {background-color: #ddd;}

#c4ytable th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #00A8A9;
    color: white;
}
div.a {
    text-align: left;
    font-family: monospace;
}
</style>

<?php

    header("Access-Control-Allow-Origin: *");
    header("Access-Control-Allow-Methods: GET");

    $servername = "localhost";
    $username   = "HeidiTracker";
    $password   = "";
    $dbname     = "Heidi";
    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
        echo "Database Connection failed: " . $conn->connect_error;
        die("Database Connection failed: " . $conn->connect_error);
    }

    $TrackerID = $_GET['ID'];
    if (isset($_GET['StartDate'])) {$StartDate = $_GET['StartDate']; } 
    else { $StartDate = date('Y-m-d') . " 00:00:00"; }
    if (isset($_GET['EndDate'])) {$EndDate = $_GET['EndDate']; } 
    else { $EndDate = date('Y-m-d') . " 23:59:59"; }
    $Table     = "TrackerData";
    if (isset($_GET['ShowData'])) { $Action = $_GET['ShowData']; } 
    else { $Action = "TAB"; } 

    $LocalStartDate = date_create_from_format('Y-m-d H:i:s', $StartDate);
    $StartDateUTC = gmdate('Y-m-d H:i:s', date_timestamp_get($LocalStartDate));
    $LocalEndDate = date_create_from_format('Y-m-d H:i:s', $EndDate);
    $EndDateUTC = gmdate('Y-m-d H:i:s', date_timestamp_get($LocalEndDate));
    
?>

<div id="cards" class="cards"> 
<?php 
  echo "Tracker: "; 
  echo "<input id=\"NewTrackerID\" type=\"text\" size=\"10\" onclick=\"\" value=\"" . $TrackerID . "\">";
  echo " von "; 
  echo "<input id=\"NewStartDate\" type=\"date\" onclick=\"\" value=\"" . date_format($LocalStartDate, "Y-m-d") . "\">";
  echo " bis "; 
  echo "<input id=\"NewEndDate\" type=\"date\" onclick=\"\" value=\"" . date_format($LocalEndDate, "Y-m-d") . "\"> ";
  echo "<input id=\"ReLoad\" type=\"button\" onclick=\"ReloadPage()\" value=\"reload\"> ";
  echo "<button onclick=\"exportToExcel()\">Export To Excel</button>";
  echo "<br><br>"; 
?>

<?php
    
    //          row    0         1          2         3         4          5            6           7            8          9          10         11 
    //                                                                                             Sats       GPShdop     acc1        acc2        Mout 
    $sql  = "SELECT Longitude, Latitude, Altitude, TimeStamp, Battery, Temperature, ErrorCode, FreeValue1, FreeValue2, FreeValue3, FreeValue4, FreeValue5 FROM TrackerData ";
    $sql .= "WHERE TrackerID = '{$TrackerID}' AND TimeStamp >= '{$StartDateUTC }' AND TimeStamp <= '{$EndDateUTC}' ";
    $sql .= "ORDER BY TimeStamp DESC";

    if ($result=mysqli_query($conn,$sql))
      {
      if ($Action == "GPX") {
        echo "<div class=\"a\">";
        echo "&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;<br>";
        echo "&lt;gpx version=&quot;1.0&quot;&gt;<br>";
        echo "&emsp;&lt;name&gt;Heidi track&lt;/name&gt;<br>";
        echo "&emsp;&lt;trk&gt;&lt;name&gt;{$TrackerID}&lt;/name&gt;&lt;trkseg&gt;<br>";
      } else {
        echo "<table id='c4ytable'>";
        echo "<tr><th>Zeit</th><th>Laenge</th><th>Breite</th><th>Entfernung</th><th>BWidx1</th><th>BWidx2</th><th>Batterie</th><th>Temp.</th><th>Sats</th><th>GPShdop</th><th>ErrorCode</th></tr>";
      }
      // Fetch one and one row
      $tz = new DateTimeZone( "UTC" );
      while ($row=mysqli_fetch_row($result))
      {
        if ($Action == "GPX") {
          $d = date_create_from_format("Y-m-d H:i:s", $row[4]);
          echo "&emsp;&emsp;&lt;trkpt lat=&quot;" . $row[2] . "&quot; lon=&quot;" . $row[1]."&quot;&gt;";
          echo "&lt;time&gt;" . date_format($d,"y-m-d") . "T" . date_format($d,"H:i:s") . "Z&lt;/time&gt;&lt;/trkpt&gt;";
          echo "<br>";
        } else {
          
          $MeasDateUTC = date_create_from_format('Y-m-d H:i:s', $row[3], $tz);
          $MeasDate = date('Y-m-d H:i:s', date_timestamp_get($MeasDateUTC));
          echo "<tr><td>".$MeasDate."</td><td>".$row[0]."</td><td>".$row[1]."</td><td>".$row[11]."</td><td>".$row[9]."</td><td>".$row[10];
          echo "</td><td>".$row[4]."</td><td>".$row[5]."</td><td>".$row[7]."</td><td>".$row[8]."</td><td>".$row[6]."</td></tr>";
        }
      }

      if ($Action == "GPX") {
        echo "&emsp;&lt;/trkseg&gt;&lt;/trk&gt;<br>";
        echo "&lt;/gpx&gt;<br>";
        echo "</div";
      } else {
        echo "</table>";
      }
      // Free result set
      mysqli_free_result($result);
    } else {
      echo "empty result";
    }

    mysqli_close($conn);
?>
<script>

  function ReloadPage(){
    //console.log("redirect : show_data.phtml?ID=" + document.getElementById("NewTrackerID").value + "&StartDate=" + document.getElementById("NewStartDate").value + " 00:00:00&EndDate=" + document.getElementById("NewEndDate").value + " 23:59:59");
    window.location.replace("show_data.phtml?ID=" + document.getElementById("NewTrackerID").value + "&StartDate=" + document.getElementById("NewStartDate").value + " 00:00:00&EndDate=" + document.getElementById("NewEndDate").value + " 23:59:59");
  }
  
  function exportToExcel(){  
    var downloadurl;  
    var dataFileType = 'application/vnd.ms-excel';  
    var tableSelect = document.getElementById('c4ytable');  
    var tableHTMLData = tableSelect.outerHTML.replace(/ /g, '%20');  
    // Specify file name  
    filename = 'HeidiData.xls';  
    // Create download link element  
    downloadurl = document.createElement("a");  
    document.body.appendChild(downloadurl);  
    if(navigator.msSaveOrOpenBlob){  
      var blob = new Blob(['\ufeff', tableHTMLData], {  
        type: dataFileType  
      });  
      navigator.msSaveOrOpenBlob( blob, filename);  
    }else{  
      // Create a link to the file  
      downloadurl.href = 'data:' + dataFileType + ', ' + tableHTMLData;  
      // Setting the file name  
      downloadurl.download = filename;  
      //triggering the function  
      downloadurl.click();  
   }
  }
   


</script>
</body>
</html>
